### ISSUE TITLE
Multi-select option for many-to-many relations

### ISSUE THREAD

**Issue by euknyaz** [euknyaz/oc-relation-dynamic-dropdown-formwidget#1]
Implement multi-select option for many-to-many relations (currently we are limited to one-to-many and one-to-one relations only).

fields.yaml
```
 user:
        label: User
        comment: 'dynamic search and autocomplete with lazy loading'
        span: left
        type: relation-dynamic-dropdown
        select: CONCAT(first_name, ' ', last_name, ' - ', email)
        limit: 10
        attributes: { multiple: 'multiple' } # reserved for many-to-many relations
```

**Multi-select demo**

![Demo](https://github.com/euknyaz/oc-relation-dynamic-dropdown-formwidget/blob/master/assets/github/multi-select-screenshot.png?raw=true)
