### ISSUE TITLE
Support of proxy fields in fields.yaml definition

### ISSUE THREAD

**Issue by euknyaz** [euknyaz/oc-relation-dynamic-dropdown-formwidget#4]
Implement support of proxy fields in fields.yaml:
```
fields:
    relation[user]:
      label: User via relation proxy field
      type: relation-dynamic-dropdown
```

Currently it's not going to work, because current implementation depends on field name.
