### ISSUE TITLE
Support of emptyOption parameter to display it in search results

### ISSUE THREAD

**Issue by euknyaz** [euknyaz/oc-relation-dynamic-dropdown-formwidget#7]
Support of emptyOption parameter to display it in search results
```
fields:
    user:
        label: Frontend User
        comment: 'dynamic search and autocomplete with lazy loading'
        span: left
        type: relation-dynamic-dropdown
        nameFrom: username
        emptyOption: None
```
