### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PrestaSafe** [euknyaz/oc-relation-dynamic-dropdown-formwidget#8]
Hi, i've embed your plugin in my plugin but it doesnt work for me: 

```yaml
 customers:
        label: User
        span: storm
        cssClass: col-md-4
        type: relation-dynamic-dropdown
        select: name
        nameFrom: mail
```

in my model: 

```php
 public $hasOne = [
        'currency' => ['\Prestasafe\Erp\Models\Currency','key' => 'id','otherKey' => 'id_currency'],
        'customers' => ['\Prestasafe\Erp\Models\Customer', 'key' => 'id','otherKey' => 'id_customer'],
    ];
```

the query in the debug bar is: 
```
select * from `prestasafe_erp_customers` where ((lower(id) LIKE '%gu%') or (lower(mail) LIKE '%gu%')) limit 20 offset 0
```

and i've well 2 results, but not showed in the select, did i missed something ? 
<img width="463" alt="Capture d’écran 2020-05-06 à 00 03 33" src="https://user-images.githubusercontent.com/4788787/81120500-22e5b080-8f2d-11ea-9a7a-92a9b65b22a0.png">

<img width="581" alt="Capture d’écran 2020-05-06 à 00 04 50" src="https://user-images.githubusercontent.com/4788787/81120545-401a7f00-8f2d-11ea-97d0-9b21b1b295a2.png">

Thanks !
